###################################
# Scenario 4 — hostPath Volume (Local Storage Practice)
# Since cloud PVs/PVCs won’t work locally without CSI drivers,
# hostPath is perfect for learning persistence.
# Concepts Practiced:
#   Persistent storage
#   hostPath volume
# Writing logs/data to host machine
####################################################################
apiVersion: v1
kind: Pod
metadata: 
  name: host-pod
spec:
  volumes:
   - name: data
     hostPath:
       path: /tmp/data
       type: DirectoryOrCreate
  containers:
  - name: host
    image: nginx:latest
    command: ["sh","-c","echo Hello > /data/file.txt; sleep 3600"]
    volumeMounts:
     - name: data
       mountPath: /data

          