apiVersion: apps/v1
kind: Deployment
metadata:
  name: iron-db-deployment-devops
  namespace: iron-namespace-devops
  labels:
    db: mariadb
spec: 
  replicas: 1
  selector:
    matchLabels:
      db: mariadb
  template:
    metadata:
      labels:
        db: mariadb
    spec:
      containers:
        - name: iron-db-container-devops
          image: kodekloud/irondb:2.0
          env:
            - name: MYSQL_DATABASE
              value: database_host
            - name: MYSQL_ROOT_PASSWORD
              value: "RootP@ssw0rd!"
            - name: MYSQL_USER
              value: "ironuser"
            - name: MYSQL_PASSWORD
              value: "IronP@ss123"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db
      volumes:
        - name: db
          emptyDir: {}


