# Writing Deployment manifest file to deploy the webserver POD with multiple containers along with replicas 3, resource limits & Shared volumesapiVersion: apps/v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: webserver
  template:
    metadata:
      labels:
        name: webserver
    spec:
       volumes:
          - name: shared-logs
            emptyDir: {}
       containers:
        - name: nginx-container
          image: nginx:latest
          volumeMounts:
            - name: shared-logs
              mountPath: /var/log/nginx
          resources:
            requests:
              memory: "20Mi"
              cpu: "100m"
            limits:
              memory: "25Mi"
              cpu: "100m"
        - name: sidecar-container
          image: ubuntu:latest
          command: ["sh","-c","while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done"]
          volumeMounts:
            - mountPath: /var/log/nginx
              name: shared-logs
          resources:
            requests:
              memory: "20Mi"
              cpu: "100m"
            limits:
              memory: "25Mi"
              cpu: "100m"
    