# First version of Yaml file for resource limits
apiVersion: v1
kind: pod
metadata:
  name: httpd-pod
spec:
  containers:
   - name: httpd-container
     image: httpd:latest
     resources:
       requests:
         memory: "15Mi"
         CPU: "100m"
       limits:
         memory: "20Mi"
         CPU: "100m"

## ran the command "kubectl apply -f resource-limit.yaml" to create the pod with resource limits and requests.
## Got the below error 
## thor@jumphost ~$ kubectl apply -f resource-limit.yaml 
## error: resource mapping not found for name: "httpd-pod" namespace: "" from "resource-limit.yaml": no matches for kind "pod" in version "apps/v1"
## ensure CRDs are installed first
## Error occired because of wrong apiVersion. Changed apiVersion to v1 and applied the file again. Now got issue with pod becuase i passed the pod instead of "Pod"
## thor@jumphost ~$ kubectl apply -f resource-limit.yaml 
## The Pod "httpd-pod" is invalid: 
## * spec.containers[0].resources.limits[CPU]: Invalid value: "CPU": must be a standard resource type or fully qualified
## * spec.containers[0].resources.limits[CPU]: Invalid value: "CPU": must be a standard resource for containers
## * spec.containers[0].resources.requests[CPU]: Invalid value: "CPU": must be a standard resource type or fully qualified
## * spec.containers[0].resources.requests[CPU]: Invalid value: "CPU": must be a standard resource for containers
## Changes the CPU to lowercase and applied the file again. Now the pod is created successfully with resource limits and requests.

## Working vesion of Yaml file for resource limits and requests for a pod running httpd container.
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
   - name: httpd-container
     image: httpd:latest
     resources:
       requests:
         memory: "15Mi"
         cpu: "100m"
       limits:
         memory: "20Mi"
         cpu: "100m"