################################################################################
# Scenario 2 — Multi‑Container Pod (Sidecar Pattern)
# A classic production pattern that works locally too.
# Concepts Practiced
#
# Multi‑container Pod
# Shared emptyDir volume
# Sidecar logging
# Busybox debugging
#
# Real-time Purpose
# Understand how logs are shared between containers.
######################################################################################
apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
      resources:
        requests:
          memory: "20Mi"
          cpu: "100m"
        limits:
          memory: "25Mi"
          cpu: "100m"
    - name: sidecar-container
      image: ubuntu:latest
      command: ["sh","-c","while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done"]
      volumeMounts:
        - mountPath: /var/log/nginx
          name: shared-logs
      resources:
        requests:
          memory: "20Mi"
          cpu: "100m"
        limits:
          memory: "25Mi"
          cpu: "100m"