#############################################################
# Scenario 1 — Simple Web App + NodePort Service          
# Local clusters don’t support load balancers by default.
# So NodePort = best local practice.
# Concepts Practiced :
# Deployment
# ReplicaSet
# NodePort Service -- Written in seperate service
# Rolling updates
# Probes
# Resource limits
# Real-time Purpose
# Expose a frontend on NodePort so you can open it in browser
####################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      name: webapp 
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers: 
        - name: webapp-1
          image: apache:latest
          ports:
            - containerPort: 80
    